
version: '3.9'

services:
    etr:
        container_name: etr
        restart: always
        image: rocker/geospatial
        volumes:
            - ${DATA_PATH}:/data
            - ./etr:/scripts
        ports:
            - "8888:8787"
        env_file:
            - ./.env